
spring:
  datasource:
    url: jdbc:h2:mem:DbProva
    driver-class-name: org.h2.Driver
    username: root
    password: toor

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

custom:
  jwt:
    secret: chiaveAbbastanzaLungaDaCodificareUnTokenJwt
    expiration: 3600000